name: Validate PR
run-name: Validate PR
on: pull_request
env:
  DOTNET_VERSION: "6.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3.0.3
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build with dotnet
        run: dotnet build --configuration Release
